# Generated by Django 4.2.7 on 2025-04-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmissionsTotals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_code", models.IntegerField()),
                ("area_code_m49", models.TextField()),
                ("area", models.TextField()),
                ("item_code", models.IntegerField()),
                ("item", models.TextField()),
                ("element_code", models.IntegerField()),
                ("element", models.TextField()),
                ("source_code", models.IntegerField()),
                ("source", models.TextField()),
                ("unit", models.TextField()),
                (
                    "Y1961",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1962",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1963",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1964",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1965",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1966",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1967",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1968",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1969",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1970",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1971",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1972",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1973",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1974",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1975",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1976",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1977",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1978",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1979",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1980",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1981",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1982",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1983",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1984",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1985",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1986",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1987",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1988",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1989",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1990",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1991",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1992",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1993",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1994",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1995",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1996",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1997",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1998",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y1999",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2000",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2001",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2002",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2003",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2004",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2005",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2006",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2007",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2008",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2009",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2010",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2011",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2012",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2013",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2014",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2015",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2016",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2017",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2018",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2019",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2020",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2021",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2022",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2030",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "Y2050",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
            ],
            options={
                "db_table": "climate_change_emissions_totals",
            },
        ),
    ]
