from django.db import models

class EmissionsTotals(models.Model):
	area_code = models.IntegerField()
	area_code_m49 = models.TextField()
	area = models.TextField()
	item_code = models.IntegerField()
	item = models.TextField()
	element_code = models.IntegerField()
	element = models.TextField()
	source_code = models.IntegerField()
	source = models.TextField()
	unit = models.TextField()
	Y1961 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1962 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1963 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1964 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1965 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1966 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1967 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1968 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1969 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1970 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1971 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1972 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1973 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1974 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1975 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1976 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1977 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1978 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1979 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1980 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1981 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1982 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1983 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1984 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1985 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1986 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1987 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1988 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1989 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1990 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1991 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1992 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1993 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1994 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1995 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1996 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1997 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1998 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y1999 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2000 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2001 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2002 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2003 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2004 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2005 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2006 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2007 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2008 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2009 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2010 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2011 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2012 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2013 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2014 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2015 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2016 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2017 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2018 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2019 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2020 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2021 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2022 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2030 = models.DecimalField(max_digits=10, null=True, decimal_places=8)
	Y2050 = models.DecimalField(max_digits=10, null=True, decimal_places=8)	
	
	class Meta:
		db_table = "climate_change_emissions_totals"
